import type { AdminRow } from "../types";

export const INITIAL_ADMINS: AdminRow[] = [
  {
    id: 1,
    name: "Nazmul Hasan",
    role: "Super Admin",
    email: "user@gmail.com",
    passwordMasked: "************",
    joinDate: "10/04/2025",
    phone: "01903527399",
    status: "ACTIVE",
    note: "Make your Best Effort...",
  },
  {
    id: 2,
    name: "Sarah Johnson",
    role: "Admin",
    email: "sarah.j@gmail.com",
    passwordMasked: "************",
    joinDate: "15/03/2025",
    phone: "01234567890",
    status: "ACTIVE",
    note: "Experienced adminin...",
  },
  {
    id: 3,
    name: "Michael Chen",
    role: "Manager",
    email: "michael.c@gmail.com",
    passwordMasked: "************",
    joinDate: "20/02/2025",
    phone: "01345678901",
    status: "ACTIVE",
    note: "Team lead for oper...",
  },
  {
    id: 4,
    name: "Emily Davis",
    role: "Sales Executive",
    email: "emily.d@gmail.com",
    passwordMasked: "************",
    joinDate: "05/01/2025",
    phone: "01456789012",
    status: "ACTIVE",
    note: "Top performer in sa...",
  },
  {
    id: 5,
    name: "James Wilson",
    role: "Employee Currier",
    email: "james.w@gmail.com",
    passwordMasked: "************",
    joinDate: "12/12/2024",
    phone: "01567890123",
    status: "INACTIVE",
    note: "Delivery specialist",
  },
  {
    id: 6,
    name: "Lisa Anderson",
    role: "Order Manager",
    email: "lisa.a@gmail.com",
    passwordMasked: "************",
    joinDate: "18/11/2024",
    phone: "01678901234",
    status: "ACTIVE",
    note: "Handles order proc...",
  },
  {
    id: 7,
    name: "Robert Taylor",
    role: "Product Manager",
    email: "robert.t@gmail.com",
    passwordMasked: "************",
    joinDate: "25/10/2024",
    phone: "01789012345",
    status: "ACTIVE",
    note: "Product catalog m...",
  },
];
