import type { CurrierRow } from "./types";

export const INITIAL_CURRIERS: CurrierRow[] = [
  {
    id: 1,
    name: "Steadfast Courier",
    description: "Real-time order tracking and bulk shipment features.",
    type: "STEADFAST",
    active: true,
    defaultNote: "Handle with care",
    api: {
      type: "STEADFAST",
      apiBaseUrl: "https://api.steadfast.com.bd/",
      apiKey: "steadfast-demo-api-key",
      secretKey: "steadfast-demo-secret",
    },
    createdAt: "9/24/2025, 11:34:36 AM",
    updatedAt: "3/26/2025, 03:54:14 PM",
  },
  {
    id: 2,
    name: "RedX Courier",
    description: "Fast delivery network with good coverage.",
    type: "REDX",
    active: true,
    defaultNote: "Preferred for Dhaka",
    api: {
      type: "REDX",
      apiBaseUrl: "https://api.redx.com.bd/",
      storeId: "REDX-STORE-001",
      apiToken: "redx-demo-token",
    },
    createdAt: "9/24/2025, 11:34:36 AM",
    updatedAt: "3/26/2025, 03:54:14 PM",
  },
  {
    id: 3,
    name: "Pathao Courier",
    description: "On-demand deliveries and tracking features.",
    type: "PATHAO",
    active: true,
    defaultNote: "Use for express delivery",
    api: {
      type: "PATHAO",
      apiBaseUrl: "https://api.pathao.com/",
      storeId: "PATHAO-STORE-01",
      clientId: "pathao-client-id",
      clientSecret: "pathao-client-secret",
      clientEmail: "merchant@pathao.com",
      clientPassword: "********",
    },
    createdAt: "9/24/2025, 11:34:36 AM",
    updatedAt: "3/26/2025, 03:54:14 PM",
  },
  {
    id: 4,
    name: "Paperfly Courier",
    description: "Nationwide delivery solutions with COD support.",
    type: "PAPERFLY",
    active: true,
    defaultNote: "Outside area shipments",
    api: {
      type: "PAPERFLY",
      apiBaseUrl: "https://api.paperfly.com.bd/",
      username: "paperfly_user",
      password: "********",
      apiKey: "paperfly-demo-api-key",
    },
    createdAt: "9/24/2025, 11:34:36 AM",
    updatedAt: "3/26/2025, 03:54:14 PM",
  },
];
