import Input from "@/components/form/input/InputField";
import Section from "./Section";
import Select from "@/components/form/Select";
import { Package } from "lucide-react";
import { useTranslation } from "react-i18next";

type Option = { value: string; label: string; status?: boolean };

function FieldLabel({ children }: { children: React.ReactNode }) {
  return (
    <p className="mb-1.5 text-[11px] font-semibold uppercase tracking-wider text-gray-500 dark:text-gray-400">
      {children}
    </p>
  );
}

function BasicSection({
  productName,
  setProductName,
  productSlug,
  mainCategoryId,
  setMainCategoryId,
  subCategoryId,
  setSubCategoryId,
  childCategoryId,
  setChildCategoryId,
  brandId,
  setBrandId,

  mainOptions,
  subOptions,
  childOptions,
  brandOptions,

  subLoading,
  childLoading,
}: {
  productName: string;
  setProductName: (v: string) => void;
  productSlug: string;

  mainCategoryId: number;
  setMainCategoryId: (n: number) => void;
  subCategoryId: number;
  setSubCategoryId: (n: number) => void;
  childCategoryId: number;
  setChildCategoryId: (n: number) => void;
  brandId: number;
  setBrandId: (n: number) => void;

  mainOptions: Option[];
  subOptions: Option[];
  childOptions: Option[];
  brandOptions: Option[];

  subLoading: boolean;
  childLoading: boolean;
}) {
  const { t } = useTranslation();
  return (
    <Section
      title={t("products.createProduct.basicInfoTitle")}
      description={t("products.createProduct.basicInfoDesc")}
      icon={<Package className="h-5 w-5" />}
    >
      <div className="grid grid-cols-1 gap-5 lg:grid-cols-2">
        <div>
          <FieldLabel>{t("products.createProduct.productNameLabel")} *</FieldLabel>
          <Input
            value={productName}
            onChange={(e) => setProductName(String(e.target.value))}
            placeholder={t("products.createProduct.enterProductName")}
          />
        </div>

        <div>
          <FieldLabel>{t("products.createProduct.slugLabel")}</FieldLabel>
          <Input value={productSlug} disabled placeholder={t("products.createProduct.autoGeneratedSlug")} />
        </div>

        <div>
          <FieldLabel>{t("products.createProduct.mainCategoryLabel")} *</FieldLabel>
          <Select
            options={mainOptions}
            placeholder={t("products.createProduct.selectMainCategory")}
            value={String(mainCategoryId)}
            onChange={(v) => setMainCategoryId(Number(v))}
          />
        </div>

        <div>
          <FieldLabel>{t("products.createProduct.subCategoryLabel")} *</FieldLabel>
          <Select
            key={`sub-${mainCategoryId}-${subCategoryId}`}
            options={subOptions}
            placeholder={
              subLoading
                ? t("products.createProduct.loadingSub")
                : t("products.createProduct.selectSubCategory")
            }
            value={String(subCategoryId)}
            onChange={(v) => setSubCategoryId(Number(v))}
          />
        </div>

        <div>
          <FieldLabel>{t("products.createProduct.childCategoryLabel")}</FieldLabel>
          <Select
            key={`child-${subCategoryId}-${childCategoryId}`}
            options={childOptions}
            placeholder={
              !subCategoryId
                ? t("products.createProduct.selectSubFirst")
                : childLoading
                  ? t("products.createProduct.loadingChild")
                  : t("products.createProduct.selectChildCategory")
            }
            value={String(childCategoryId)}
            onChange={(v) => setChildCategoryId(Number(v))}
          />
        </div>

        <div>
          <FieldLabel>{t("products.createProduct.brandLabel")} *</FieldLabel>
          <Select
            options={brandOptions}
            placeholder={t("products.createProduct.selectBrand")}
            value={String(brandId)}
            onChange={(v) => setBrandId(Number(v))}
          />
        </div>
      </div>
    </Section>
  );
}

export default BasicSection;
