import type { PaymentGatewayConfig } from "./types";

export const INITIAL_PAYMENT_GATEWAYS: PaymentGatewayConfig[] = [
  {
    id: 1,
    provider: "bkash",
    name: "bKash",
    category: "Mobile Banking",
    status: true,
    sandbox: true,
    note: "Tokenized checkout (sandbox)",
    createdAt: "2025-12-22 11:40 PM",
    updatedAt: "2025-12-22 11:40 PM",
    credentials: {
      baseUrl: "https://tokenized.sandbox.bka.sh/v1.2.0-beta",
      username: "sandboxTestUser",
      password: "********",
      appKey: "********",
      appSecret: "********",
    },
  },
  {
    id: 2,
    provider: "sslcommerz",
    name: "SSLCommerz",
    category: "Payment Gateway",
    status: false,
    sandbox: true,
    note: "Enable when ready",
    createdAt: "2025-12-22 11:40 PM",
    updatedAt: "2025-12-22 11:40 PM",
    credentials: {
      storeId: "",
      storePassword: "",
      apiBaseUrl: "https://sandbox.sslcommerz.com",
      successUrl: "",
      failUrl: "",
      cancelUrl: "",
    },
  },
  {
    id: 3,
    provider: "shurjopay",
    name: "ShurjoPay",
    category: "Payment Gateway",
    status: false,
    sandbox: true,
    note: "",
    createdAt: "2025-12-22 11:40 PM",
    updatedAt: "2025-12-22 11:40 PM",
    credentials: {
      endpoint: "",
      username: "",
      password: "",
      prefix: "",
      clientIp: "",
    },
  },
  {
    id: 4,
    provider: "nagad",
    name: "Nagad",
    category: "Mobile Banking",
    status: false,
    sandbox: true,
    note: "",
    createdAt: "2025-12-22 11:40 PM",
    updatedAt: "2025-12-22 11:40 PM",
    credentials: {
      baseUrl: "",
      merchantId: "",
      merchantPrivateKey: "",
      merchantPublicKey: "",
    },
  },
  {
    id: 5,
    provider: "rocket",
    name: "Rocket",
    category: "Mobile Banking",
    status: false,
    sandbox: false,
    note: "Manual bank transfer style",
    createdAt: "2025-12-22 11:40 PM",
    updatedAt: "2025-12-22 11:40 PM",
    credentials: {
      accountNo: "",
      accountName: "",
      bankName: "Dutch-Bangla Bank",
      note: "",
    },
  },
];
