import type { Product } from "./types";

export const demoProducts: Product[] = [
  {
    id: "P-1001",
    sku: "SKU-CLN-001",
    name: "Multi-Purpose Cleaner",
    imageUrl: "/images/products/cleaner.png",
    positionNumber: 1,
    categoryPath: { category: "Cleaning" },
    stockQty: 99,
    price: 10,
    discount: 0,
    salePrice: 10,
    status: "active",
    createdAt: "Oct 12, 2025",
  },
  {
    id: "P-1002",
    sku: "SKU-CLN-002",
    name: "Bathroom Foam Cleaner",
    imageUrl: "/images/products/foam.png",
    positionNumber: 2,
    categoryPath: { category: "Cleaning" },
    stockQty: 500,
    price: 25,
    discount: 0,
    salePrice: 25,
    status: "active",
    createdAt: "Oct 11, 2025",
  },
  {
    id: "P-1003",
    sku: "SKU-FOOD-020",
    name: "Lay's Classic Chips",
    imageUrl: "/images/products/chips.png",
    positionNumber: 3,
    categoryPath: { category: "Dairy & Eggs", subCategory: "Snacks", childCategory: "Chips" },
    stockQty: 3000,
    price: 80,
    discount: 10,
    salePrice: 72,
    status: "active",
    createdAt: "Oct 10, 2025",
  },
  {
    id: "P-1004",
    sku: "SKU-SPC-011",
    name: "Tones Mild Chili Powder",
    imageUrl: "/images/products/spice.png",
    positionNumber: 4,
    categoryPath: { category: "Dairy & Eggs", subCategory: "Spices" },
    stockQty: 8,
    price: 100,
    discount: 0,
    salePrice: 100,
    status: "inactive",
    createdAt: "Oct 09, 2025",
  },
  {
    id: "P-1005",
    sku: "SKU-FOOD-033",
    name: "Premium Aromatic Atta",
    imageUrl: "/images/products/atta.png",
    positionNumber: 5,
    categoryPath: { category: "Dairy & Eggs", subCategory: "Grocery", childCategory: "Flour" },
    stockQty: 5000,
    price: 300,
    discount: 15,
    salePrice: 255,
    status: "active",
    createdAt: "Oct 08, 2025",
  },
  {
    id: "P-1006",
    sku: "SKU-VEG-005",
    name: "Fresh Green Peas",
    imageUrl: "/images/products/peas.png",
    positionNumber: 6,
    categoryPath: { category: "Dairy & Eggs", subCategory: "Vegetables" },
    stockQty: 997,
    price: 1000,
    discount: 0,
    salePrice: 1000,
    status: "active",
    createdAt: "Oct 07, 2025",
  },
];
